### ISSUE TITLE
Unknown Error after Registering a new account

### ISSUE THREAD

**Issue by twizzayy** [agmm/standalone-rpi#3]
Hey, I am really new to self-hosting. Standard notes is my second project after Nextcloud. Please forgive my ignorance. I am not really sure how to troubleshoot this.

I have a brand new RPi 4b.

After running this installation and attempting to register an account from the desktop app and from the standard notes web app, I receive an unknown error.

I'm not sure what to do. I can't seem to create an account. I have run `sudo bash ./server.sh logs` and  `sudo bash ./server.sh status` and everything seems to be running correctly.

Would you mind helping point me a direction that would help me figure this out?

**Comment by 2dRYoMz7XKx3Bii** [comment]
I too have the same problem. My hardware & software is *Raspberry Pi 400 Linux debian-laptop 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux*. I think it's due to this part "You've configured a domain name (or subdomain) to point to your server's IP address." (last part in the image) because I can't otherwise resolve the raspberrypi.local host. Now I'm creating another domain [here](https://www.noip.com) and try again with the same settings!

![screenshot-docs standardnotes com-2022 04 26-18_09_17](https://user-images.githubusercontent.com/77741077/165344706-8f9c5c5f-3d0b-4966-bada-052b1dbf2ced.png)

**Comment by twizzayy** [comment]
No longer relevant
